file = open("marks.txt", "r")
file_new = open("marks1.txt", "w")
count = int(file.readline())
file_new.write(str(count)+'\n')
for i in range(count):
    rollno = int(file.readline())
    file_new.write(str(rollno)+'\n')
    m1 = int(file.readline())
    m2 = int(file.readline())
    m3 = int(file.readline())
    m4 = int(file.readline())
    file_new.write(f'{m1} {m2} {m3} {m4}\n')
file.close()
file_new.close()
